package com.self.learning.common.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table good_like_status
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class GoodLikeStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_like_status.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_like_status.g_id
     *
     * @mbg.generated
     */
    private String gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_like_status.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_like_status.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_like_status.id
     *
     * @return the value of good_like_status.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_like_status.id
     *
     * @param id the value for good_like_status.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_like_status.g_id
     *
     * @return the value of good_like_status.g_id
     *
     * @mbg.generated
     */
    public String getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_like_status.g_id
     *
     * @param gId the value for good_like_status.g_id
     *
     * @mbg.generated
     */
    public void setgId(String gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_like_status.user_id
     *
     * @return the value of good_like_status.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_like_status.user_id
     *
     * @param userId the value for good_like_status.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_like_status.status
     *
     * @return the value of good_like_status.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_like_status.status
     *
     * @param status the value for good_like_status.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}