package com.self.learning.common.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wx
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Wx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   微信号的openid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     * Database Column Remarks:
     *   微信昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   性别(1男/2女)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     *   语言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.lang
     *
     * @mbg.generated
     */
    private String lang;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * Database Column Remarks:
     *   头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.headimgurl
     *
     * @mbg.generated
     */
    private String headimgurl;

    /**
     * Database Column Remarks:
     *   特权
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx.privilege
     *
     * @mbg.generated
     */
    private String privilege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.id
     *
     * @return the value of wx.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.id
     *
     * @param id the value for wx.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.openid
     *
     * @return the value of wx.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.openid
     *
     * @param openid the value for wx.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.nickname
     *
     * @return the value of wx.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.nickname
     *
     * @param nickname the value for wx.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.sex
     *
     * @return the value of wx.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.sex
     *
     * @param sex the value for wx.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.lang
     *
     * @return the value of wx.lang
     *
     * @mbg.generated
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.lang
     *
     * @param lang the value for wx.lang
     *
     * @mbg.generated
     */
    public void setLang(String lang) {
        this.lang = lang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.city
     *
     * @return the value of wx.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.city
     *
     * @param city the value for wx.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.province
     *
     * @return the value of wx.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.province
     *
     * @param province the value for wx.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.country
     *
     * @return the value of wx.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.country
     *
     * @param country the value for wx.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.headimgurl
     *
     * @return the value of wx.headimgurl
     *
     * @mbg.generated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.headimgurl
     *
     * @param headimgurl the value for wx.headimgurl
     *
     * @mbg.generated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx.privilege
     *
     * @return the value of wx.privilege
     *
     * @mbg.generated
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx.privilege
     *
     * @param privilege the value for wx.privilege
     *
     * @mbg.generated
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }
}