package com.self.learning.common.dto;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table wx_and_phone
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class WxAndPhone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_and_phone.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   微信号的openid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_and_phone.openid
     *
     * @mbg.generated
     */
    private String openid;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_and_phone.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_and_phone.id
     *
     * @return the value of wx_and_phone.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_and_phone.id
     *
     * @param id the value for wx_and_phone.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_and_phone.openid
     *
     * @return the value of wx_and_phone.openid
     *
     * @mbg.generated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_and_phone.openid
     *
     * @param openid the value for wx_and_phone.openid
     *
     * @mbg.generated
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_and_phone.phone
     *
     * @return the value of wx_and_phone.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_and_phone.phone
     *
     * @param phone the value for wx_and_phone.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}