package com.self.learning.provider.mapper;

import com.self.learning.common.dto.GoodLikeStatus;
import com.self.learning.common.dto.GoodLikeStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodLikeStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    long countByExample(GoodLikeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    int deleteByExample(GoodLikeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    int insert(GoodLikeStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    int insertSelective(GoodLikeStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    List<GoodLikeStatus> selectByExample(GoodLikeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    GoodLikeStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodLikeStatus record, @Param("example") GoodLikeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodLikeStatus record, @Param("example") GoodLikeStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodLikeStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_like_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodLikeStatus record);

    void truncate();
}