package com.self.learning.provider.mapper;

import com.self.learning.common.dto.WxAndPhone;
import com.self.learning.common.dto.WxAndPhoneExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxAndPhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    long countByExample(WxAndPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    int deleteByExample(WxAndPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    int insert(WxAndPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    int insertSelective(WxAndPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    List<WxAndPhone> selectByExample(WxAndPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    WxAndPhone selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WxAndPhone record, @Param("example") WxAndPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WxAndPhone record, @Param("example") WxAndPhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WxAndPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_and_phone
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WxAndPhone record);
}