package com.self.learning.provider.mapper;

import com.self.learning.common.dto.Wx;
import com.self.learning.common.dto.WxExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    long countByExample(WxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    int deleteByExample(WxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    int insert(Wx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    int insertSelective(Wx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    List<Wx> selectByExample(WxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    Wx selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Wx record, @Param("example") WxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Wx record, @Param("example") WxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Wx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Wx record);
}